version: 0.2

phases:
  install:
    commands:
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
    - npm run test

artifacts:
  files:
  - buildspec.yml
  - configs.js
  - handler.js
  - package.json
  - package-lock.json
  - handler.spec.js
  - serverless.yml
  - deploy.sh